services:
  api:
    build: .
    container_name: dean_office_api
    ports:
      - "3010:3010"
    volumes:
      - .:/app_code # Hot-reload коду
      - db_data:/app_code/data # Персистентність БД
    environment:
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=my-dev-secret-key-32-chars-long!!
    restart: unless-stopped

volumes:
  db_data: